/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: ecalc_usr.i */

#define SWIGMODULE ecalc
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


/* Includes the header in the wrapper code */
#include "/usr/include/ecal/ecalc.h"
#include "/usr/include/ecal/ecal_os.h"
#include "/usr/include/ecal/ecal_defs.h"
#include "/usr/include/ecal/cimpl/ecal_callback_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_core_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_event_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_init_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_log_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_monitoring_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_process_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_publisher_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_qos_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_service_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_subscriber_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_proto_dyn_json_subscriber_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_time_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_timer_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_tlayer_cimpl.h"
#include "/usr/include/ecal/cimpl/ecal_util_cimpl.h"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_ecalc_5c8096034791d065(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_ecalc_5c8096034791d065(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_ECAL_VERSION_MAJOR_ecalc_5c8096034791d065() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)((5));
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ECAL_VERSION_MINOR_ecalc_5c8096034791d065() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)((7));
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_ECAL_VERSION_PATCH_ecalc_5c8096034791d065() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)((2));
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_ECAL_PLATFORMTOOLSET_ecalc_5c8096034791d065() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)("");
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_sub_event_none_ecalc_5c8096034791d065() {
  enum eCAL_Subscriber_Event result;
  intgo _swig_go_result;
  
  
  result = sub_event_none;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_sub_event_connected_ecalc_5c8096034791d065() {
  enum eCAL_Subscriber_Event result;
  intgo _swig_go_result;
  
  
  result = sub_event_connected;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_sub_event_disconnected_ecalc_5c8096034791d065() {
  enum eCAL_Subscriber_Event result;
  intgo _swig_go_result;
  
  
  result = sub_event_disconnected;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_sub_event_dropped_ecalc_5c8096034791d065() {
  enum eCAL_Subscriber_Event result;
  intgo _swig_go_result;
  
  
  result = sub_event_dropped;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_sub_event_timeout_ecalc_5c8096034791d065() {
  enum eCAL_Subscriber_Event result;
  intgo _swig_go_result;
  
  
  result = sub_event_timeout;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_sub_event_corrupted_ecalc_5c8096034791d065() {
  enum eCAL_Subscriber_Event result;
  intgo _swig_go_result;
  
  
  result = sub_event_corrupted;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_pub_event_none_ecalc_5c8096034791d065() {
  enum eCAL_Publisher_Event result;
  intgo _swig_go_result;
  
  
  result = pub_event_none;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_pub_event_connected_ecalc_5c8096034791d065() {
  enum eCAL_Publisher_Event result;
  intgo _swig_go_result;
  
  
  result = pub_event_connected;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_pub_event_disconnected_ecalc_5c8096034791d065() {
  enum eCAL_Publisher_Event result;
  intgo _swig_go_result;
  
  
  result = pub_event_disconnected;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_pub_event_dropped_ecalc_5c8096034791d065() {
  enum eCAL_Publisher_Event result;
  intgo _swig_go_result;
  
  
  result = pub_event_dropped;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_reg_event_none_ecalc_5c8096034791d065() {
  enum eCAL_Registration_Event result;
  intgo _swig_go_result;
  
  
  result = reg_event_none;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_reg_event_publisher_ecalc_5c8096034791d065() {
  enum eCAL_Registration_Event result;
  intgo _swig_go_result;
  
  
  result = reg_event_publisher;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_reg_event_subscriber_ecalc_5c8096034791d065() {
  enum eCAL_Registration_Event result;
  intgo _swig_go_result;
  
  
  result = reg_event_subscriber;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_reg_event_service_ecalc_5c8096034791d065() {
  enum eCAL_Registration_Event result;
  intgo _swig_go_result;
  
  
  result = reg_event_service;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_reg_event_process_ecalc_5c8096034791d065() {
  enum eCAL_Registration_Event result;
  intgo _swig_go_result;
  
  
  result = reg_event_process;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_SReceiveCallbackDataC_buf_set_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0, void *_swig_go_1) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  void *arg2 = (void *) 0 ;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  
  if (arg1) (arg1)->buf = arg2;
  
}


void *_wrap_SReceiveCallbackDataC_buf_get_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  
  result = (void *) ((arg1)->buf);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_SReceiveCallbackDataC_size_set_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0, long long _swig_go_1) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  long arg2 ;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  if (arg1) (arg1)->size = arg2;
  
}


long long _wrap_SReceiveCallbackDataC_size_get_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  
  result = (long) ((arg1)->size);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SReceiveCallbackDataC_id_set_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0, long long _swig_go_1) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  long long arg2 ;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  arg2 = (long long)_swig_go_1; 
  
  if (arg1) (arg1)->id = arg2;
  
}


long long _wrap_SReceiveCallbackDataC_id_get_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  long long result;
  long long _swig_go_result;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  
  result = (long long) ((arg1)->id);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SReceiveCallbackDataC_time_set_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0, long long _swig_go_1) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  long long arg2 ;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  arg2 = (long long)_swig_go_1; 
  
  if (arg1) (arg1)->time = arg2;
  
}


long long _wrap_SReceiveCallbackDataC_time_get_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  long long result;
  long long _swig_go_result;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  
  result = (long long) ((arg1)->time);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SReceiveCallbackDataC_clock_set_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0, long long _swig_go_1) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  long long arg2 ;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  arg2 = (long long)_swig_go_1; 
  
  if (arg1) (arg1)->clock = arg2;
  
}


long long _wrap_SReceiveCallbackDataC_clock_get_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  long long result;
  long long _swig_go_result;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  
  result = (long long) ((arg1)->clock);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct SReceiveCallbackDataC *_wrap_new_SReceiveCallbackDataC_ecalc_5c8096034791d065() {
  struct SReceiveCallbackDataC *result = 0 ;
  struct SReceiveCallbackDataC *_swig_go_result;
  
  
  result = (struct SReceiveCallbackDataC *)calloc(1, sizeof(struct SReceiveCallbackDataC));
  *(struct SReceiveCallbackDataC **)&_swig_go_result = (struct SReceiveCallbackDataC *)result; 
  return _swig_go_result;
}


void _wrap_delete_SReceiveCallbackDataC_ecalc_5c8096034791d065(struct SReceiveCallbackDataC *_swig_go_0) {
  struct SReceiveCallbackDataC *arg1 = (struct SReceiveCallbackDataC *) 0 ;
  
  arg1 = *(struct SReceiveCallbackDataC **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_SPubEventCallbackDataC_Xtype_set_ecalc_5c8096034791d065(struct SPubEventCallbackDataC *_swig_go_0, intgo _swig_go_1) {
  struct SPubEventCallbackDataC *arg1 = (struct SPubEventCallbackDataC *) 0 ;
  enum eCAL_Publisher_Event arg2 ;
  
  arg1 = *(struct SPubEventCallbackDataC **)&_swig_go_0; 
  arg2 = (enum eCAL_Publisher_Event)_swig_go_1; 
  
  if (arg1) (arg1)->type = arg2;
  
}


intgo _wrap_SPubEventCallbackDataC_Xtype_get_ecalc_5c8096034791d065(struct SPubEventCallbackDataC *_swig_go_0) {
  struct SPubEventCallbackDataC *arg1 = (struct SPubEventCallbackDataC *) 0 ;
  enum eCAL_Publisher_Event result;
  intgo _swig_go_result;
  
  arg1 = *(struct SPubEventCallbackDataC **)&_swig_go_0; 
  
  result = (enum eCAL_Publisher_Event) ((arg1)->type);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_SPubEventCallbackDataC_time_set_ecalc_5c8096034791d065(struct SPubEventCallbackDataC *_swig_go_0, long long _swig_go_1) {
  struct SPubEventCallbackDataC *arg1 = (struct SPubEventCallbackDataC *) 0 ;
  long long arg2 ;
  
  arg1 = *(struct SPubEventCallbackDataC **)&_swig_go_0; 
  arg2 = (long long)_swig_go_1; 
  
  if (arg1) (arg1)->time = arg2;
  
}


long long _wrap_SPubEventCallbackDataC_time_get_ecalc_5c8096034791d065(struct SPubEventCallbackDataC *_swig_go_0) {
  struct SPubEventCallbackDataC *arg1 = (struct SPubEventCallbackDataC *) 0 ;
  long long result;
  long long _swig_go_result;
  
  arg1 = *(struct SPubEventCallbackDataC **)&_swig_go_0; 
  
  result = (long long) ((arg1)->time);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SPubEventCallbackDataC_clock_set_ecalc_5c8096034791d065(struct SPubEventCallbackDataC *_swig_go_0, long long _swig_go_1) {
  struct SPubEventCallbackDataC *arg1 = (struct SPubEventCallbackDataC *) 0 ;
  long long arg2 ;
  
  arg1 = *(struct SPubEventCallbackDataC **)&_swig_go_0; 
  arg2 = (long long)_swig_go_1; 
  
  if (arg1) (arg1)->clock = arg2;
  
}


long long _wrap_SPubEventCallbackDataC_clock_get_ecalc_5c8096034791d065(struct SPubEventCallbackDataC *_swig_go_0) {
  struct SPubEventCallbackDataC *arg1 = (struct SPubEventCallbackDataC *) 0 ;
  long long result;
  long long _swig_go_result;
  
  arg1 = *(struct SPubEventCallbackDataC **)&_swig_go_0; 
  
  result = (long long) ((arg1)->clock);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct SPubEventCallbackDataC *_wrap_new_SPubEventCallbackDataC_ecalc_5c8096034791d065() {
  struct SPubEventCallbackDataC *result = 0 ;
  struct SPubEventCallbackDataC *_swig_go_result;
  
  
  result = (struct SPubEventCallbackDataC *)calloc(1, sizeof(struct SPubEventCallbackDataC));
  *(struct SPubEventCallbackDataC **)&_swig_go_result = (struct SPubEventCallbackDataC *)result; 
  return _swig_go_result;
}


void _wrap_delete_SPubEventCallbackDataC_ecalc_5c8096034791d065(struct SPubEventCallbackDataC *_swig_go_0) {
  struct SPubEventCallbackDataC *arg1 = (struct SPubEventCallbackDataC *) 0 ;
  
  arg1 = *(struct SPubEventCallbackDataC **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_SSubEventCallbackDataC_Xtype_set_ecalc_5c8096034791d065(struct SSubEventCallbackDataC *_swig_go_0, intgo _swig_go_1) {
  struct SSubEventCallbackDataC *arg1 = (struct SSubEventCallbackDataC *) 0 ;
  enum eCAL_Subscriber_Event arg2 ;
  
  arg1 = *(struct SSubEventCallbackDataC **)&_swig_go_0; 
  arg2 = (enum eCAL_Subscriber_Event)_swig_go_1; 
  
  if (arg1) (arg1)->type = arg2;
  
}


intgo _wrap_SSubEventCallbackDataC_Xtype_get_ecalc_5c8096034791d065(struct SSubEventCallbackDataC *_swig_go_0) {
  struct SSubEventCallbackDataC *arg1 = (struct SSubEventCallbackDataC *) 0 ;
  enum eCAL_Subscriber_Event result;
  intgo _swig_go_result;
  
  arg1 = *(struct SSubEventCallbackDataC **)&_swig_go_0; 
  
  result = (enum eCAL_Subscriber_Event) ((arg1)->type);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_SSubEventCallbackDataC_time_set_ecalc_5c8096034791d065(struct SSubEventCallbackDataC *_swig_go_0, long long _swig_go_1) {
  struct SSubEventCallbackDataC *arg1 = (struct SSubEventCallbackDataC *) 0 ;
  long long arg2 ;
  
  arg1 = *(struct SSubEventCallbackDataC **)&_swig_go_0; 
  arg2 = (long long)_swig_go_1; 
  
  if (arg1) (arg1)->time = arg2;
  
}


long long _wrap_SSubEventCallbackDataC_time_get_ecalc_5c8096034791d065(struct SSubEventCallbackDataC *_swig_go_0) {
  struct SSubEventCallbackDataC *arg1 = (struct SSubEventCallbackDataC *) 0 ;
  long long result;
  long long _swig_go_result;
  
  arg1 = *(struct SSubEventCallbackDataC **)&_swig_go_0; 
  
  result = (long long) ((arg1)->time);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SSubEventCallbackDataC_clock_set_ecalc_5c8096034791d065(struct SSubEventCallbackDataC *_swig_go_0, long long _swig_go_1) {
  struct SSubEventCallbackDataC *arg1 = (struct SSubEventCallbackDataC *) 0 ;
  long long arg2 ;
  
  arg1 = *(struct SSubEventCallbackDataC **)&_swig_go_0; 
  arg2 = (long long)_swig_go_1; 
  
  if (arg1) (arg1)->clock = arg2;
  
}


long long _wrap_SSubEventCallbackDataC_clock_get_ecalc_5c8096034791d065(struct SSubEventCallbackDataC *_swig_go_0) {
  struct SSubEventCallbackDataC *arg1 = (struct SSubEventCallbackDataC *) 0 ;
  long long result;
  long long _swig_go_result;
  
  arg1 = *(struct SSubEventCallbackDataC **)&_swig_go_0; 
  
  result = (long long) ((arg1)->clock);
  _swig_go_result = result; 
  return _swig_go_result;
}


struct SSubEventCallbackDataC *_wrap_new_SSubEventCallbackDataC_ecalc_5c8096034791d065() {
  struct SSubEventCallbackDataC *result = 0 ;
  struct SSubEventCallbackDataC *_swig_go_result;
  
  
  result = (struct SSubEventCallbackDataC *)calloc(1, sizeof(struct SSubEventCallbackDataC));
  *(struct SSubEventCallbackDataC **)&_swig_go_result = (struct SSubEventCallbackDataC *)result; 
  return _swig_go_result;
}


void _wrap_delete_SSubEventCallbackDataC_ecalc_5c8096034791d065(struct SSubEventCallbackDataC *_swig_go_0) {
  struct SSubEventCallbackDataC *arg1 = (struct SSubEventCallbackDataC *) 0 ;
  
  arg1 = *(struct SSubEventCallbackDataC **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


_gostring_ _wrap_eCAL_GetVersionString_ecalc_5c8096034791d065() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)eCAL_GetVersionString();
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_eCAL_GetVersionDateString_ecalc_5c8096034791d065() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)eCAL_GetVersionDateString();
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_eCAL_GetVersion_ecalc_5c8096034791d065(intgo *_swig_go_0, intgo *_swig_go_1, intgo *_swig_go_2) {
  int *arg1 = (int *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(int **)&_swig_go_0; 
  arg2 = *(int **)&_swig_go_1; 
  arg3 = *(int **)&_swig_go_2; 
  
  result = (int)eCAL_GetVersion(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Initialize_ecalc_5c8096034791d065(intgo _swig_go_0, _gostring_* _swig_go_1, _gostring_ _swig_go_2, intgo _swig_go_3) {
  int arg1 ;
  char **arg2 = (char **) 0 ;
  char *arg3 = (char *) 0 ;
  unsigned int arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  arg2 = *(char ***)&_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (unsigned int)_swig_go_3; 
  
  result = (int)eCAL_Initialize(arg1,arg2,(char const *)arg3,arg4);
  _swig_go_result = result; 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_eCAL_SetUnitName_ecalc_5c8096034791d065(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (int)eCAL_SetUnitName((char const *)arg1);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Finalize_ecalc_5c8096034791d065(intgo _swig_go_0) {
  unsigned int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (unsigned int)_swig_go_0; 
  
  result = (int)eCAL_Finalize(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_IsInitialized_ecalc_5c8096034791d065(intgo _swig_go_0) {
  unsigned int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (unsigned int)_swig_go_0; 
  
  result = (int)eCAL_IsInitialized(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Ok_ecalc_5c8096034791d065() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)eCAL_Ok();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_eCAL_FreeMem_ecalc_5c8096034791d065(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  eCAL_FreeMem(arg1);
  
}


ECAL_HANDLE _wrap_eCAL_Event_gOpenEvent_ecalc_5c8096034791d065(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  ECAL_HANDLE result;
  ECAL_HANDLE _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (ECAL_HANDLE)eCAL_Event_gOpenEvent((char const *)arg1);
  *(ECAL_HANDLE *)&_swig_go_result = (ECAL_HANDLE)result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Event_gCloseEvent_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Event_gCloseEvent(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Event_gSetEvent_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Event_gSetEvent(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Event_gWaitForEvent_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, long long _swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  long arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  result = (int)eCAL_Event_gWaitForEvent(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Event_gEventIsValid_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Event_gEventIsValid(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Init_All_ecalc_5c8096034791d065() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)((0x01|0x02|0x04|0x08|0x10|0x20|0x40|0x80));
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Init_Default_ecalc_5c8096034791d065() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)((0x01|0x02|0x04|0x10|0x20|0x80));
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_eCAL_Logging_SetLogLevel_ecalc_5c8096034791d065(intgo _swig_go_0) {
  enum eCAL_Logging_eLogLevel arg1 ;
  
  arg1 = (enum eCAL_Logging_eLogLevel)_swig_go_0; 
  
  eCAL_Logging_SetLogLevel(arg1);
  
}


intgo _wrap_eCAL_Logging_GetLogLevel_ecalc_5c8096034791d065() {
  enum eCAL_Logging_eLogLevel result;
  intgo _swig_go_result;
  
  
  result = (enum eCAL_Logging_eLogLevel)eCAL_Logging_GetLogLevel();
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_eCAL_Logging_Log_ecalc_5c8096034791d065(_gostring_ _swig_go_0) {
  char *arg1 = (char *) (char *)0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  eCAL_Logging_Log((char const *)arg1);
  
  free(arg1); 
}


void _wrap_eCAL_Logging_StartCoreTimer_ecalc_5c8096034791d065() {
  eCAL_Logging_StartCoreTimer();
  
}


void _wrap_eCAL_Logging_StopCoreTimer_ecalc_5c8096034791d065() {
  eCAL_Logging_StopCoreTimer();
  
}


void _wrap_eCAL_Logging_SetCoreTime_ecalc_5c8096034791d065(double _swig_go_0) {
  double arg1 ;
  
  arg1 = (double)_swig_go_0; 
  
  eCAL_Logging_SetCoreTime(arg1);
  
}


double _wrap_eCAL_Logging_GetCoreTime_ecalc_5c8096034791d065() {
  double result;
  double _swig_go_result;
  
  
  result = (double)eCAL_Logging_GetCoreTime();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Monitoring_SetExclFilter_ecalc_5c8096034791d065(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (int)eCAL_Monitoring_SetExclFilter((char const *)arg1);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Monitoring_SetInclFilter_ecalc_5c8096034791d065(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (int)eCAL_Monitoring_SetInclFilter((char const *)arg1);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Monitoring_SetFilterState_ecalc_5c8096034791d065(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)eCAL_Monitoring_SetFilterState(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Monitoring_GetMonitoring_ecalc_5c8096034791d065(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)eCAL_Monitoring_GetMonitoring(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Monitoring_GetLogging_ecalc_5c8096034791d065(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)eCAL_Monitoring_GetLogging(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Monitoring_PubMonitoring_ecalc_5c8096034791d065(intgo _swig_go_0, _gostring_ _swig_go_1) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)eCAL_Monitoring_PubMonitoring(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Monitoring_PubLogging_ecalc_5c8096034791d065(intgo _swig_go_0, _gostring_ _swig_go_1) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)eCAL_Monitoring_PubLogging(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


void _wrap_eCAL_Process_DumpConfig_ecalc_5c8096034791d065() {
  eCAL_Process_DumpConfig();
  
}


intgo _wrap_eCAL_Process_GetHostName_ecalc_5c8096034791d065(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)eCAL_Process_GetHostName(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Process_GetHostID_ecalc_5c8096034791d065() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)eCAL_Process_GetHostID();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Process_GetUnitName_ecalc_5c8096034791d065(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)eCAL_Process_GetUnitName(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Process_GetTaskParameter_ecalc_5c8096034791d065(void *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  char *arg3 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  result = (int)eCAL_Process_GetTaskParameter(arg1,arg2,(char const *)arg3);
  _swig_go_result = result; 
  free(arg3); 
  return _swig_go_result;
}


void _wrap_eCAL_Process_SleepMS_ecalc_5c8096034791d065(long long _swig_go_0) {
  long arg1 ;
  
  arg1 = (long)_swig_go_0; 
  
  eCAL_Process_SleepMS(arg1);
  
}


intgo _wrap_eCAL_Process_GetProcessID_ecalc_5c8096034791d065() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)eCAL_Process_GetProcessID();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Process_GetProcessName_ecalc_5c8096034791d065(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)eCAL_Process_GetProcessName(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Process_GetProcessParameter_ecalc_5c8096034791d065(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)eCAL_Process_GetProcessParameter(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_eCAL_Process_GetProcessCpuUsage_ecalc_5c8096034791d065() {
  float result;
  float _swig_go_result;
  
  
  result = (float)eCAL_Process_GetProcessCpuUsage();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_eCAL_Process_GetProcessMemory_ecalc_5c8096034791d065() {
  unsigned long result;
  long long _swig_go_result;
  
  
  result = (unsigned long)eCAL_Process_GetProcessMemory();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_eCAL_Process_GetSClock_ecalc_5c8096034791d065() {
  long long result;
  long long _swig_go_result;
  
  
  result = (long long)eCAL_Process_GetSClock();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_eCAL_Process_GetSBytes_ecalc_5c8096034791d065() {
  long long result;
  long long _swig_go_result;
  
  
  result = (long long)eCAL_Process_GetSBytes();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_eCAL_Process_GetWClock_ecalc_5c8096034791d065() {
  long long result;
  long long _swig_go_result;
  
  
  result = (long long)eCAL_Process_GetWClock();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_eCAL_Process_GetWBytes_ecalc_5c8096034791d065() {
  long long result;
  long long _swig_go_result;
  
  
  result = (long long)eCAL_Process_GetWBytes();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_eCAL_Process_GetRClock_ecalc_5c8096034791d065() {
  long long result;
  long long _swig_go_result;
  
  
  result = (long long)eCAL_Process_GetRClock();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_eCAL_Process_GetRBytes_ecalc_5c8096034791d065() {
  long long result;
  long long _swig_go_result;
  
  
  result = (long long)eCAL_Process_GetRBytes();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_eCAL_Process_SetState_ecalc_5c8096034791d065(intgo _swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  enum eCAL_Process_eSeverity arg1 ;
  enum eCAL_Process_eSeverity_Level arg2 ;
  char *arg3 = (char *) 0 ;
  
  arg1 = (enum eCAL_Process_eSeverity)_swig_go_0; 
  arg2 = (enum eCAL_Process_eSeverity_Level)_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  eCAL_Process_SetState(arg1,arg2,(char const *)arg3);
  
  free(arg3); 
}


intgo _wrap_eCAL_Process_StartProcess_ecalc_5c8096034791d065(_gostring_ _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, intgo _swig_go_3, intgo _swig_go_4, intgo _swig_go_5) {
  char *arg1 = (char *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  enum eCAL_Process_eStartMode arg5 ;
  int arg6 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (int)_swig_go_3; 
  arg5 = (enum eCAL_Process_eStartMode)_swig_go_4; 
  arg6 = (int)_swig_go_5; 
  
  result = (int)eCAL_Process_StartProcess((char const *)arg1,(char const *)arg2,(char const *)arg3,arg4,arg5,arg6);
  _swig_go_result = result; 
  free(arg1); 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Process_StopProcessName_ecalc_5c8096034791d065(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (int)eCAL_Process_StopProcessName((char const *)arg1);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Process_StopProcessID_ecalc_5c8096034791d065(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)eCAL_Process_StopProcessID(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


ECAL_HANDLE _wrap_eCAL_Pub_New_ecalc_5c8096034791d065() {
  ECAL_HANDLE result;
  ECAL_HANDLE _swig_go_result;
  
  
  result = (ECAL_HANDLE)eCAL_Pub_New();
  *(ECAL_HANDLE *)&_swig_go_result = (ECAL_HANDLE)result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_Create_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, _gostring_ _swig_go_3, intgo _swig_go_4) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  arg5 = (int)_swig_go_4; 
  
  result = (int)eCAL_Pub_Create(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,arg5);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  free(arg4); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_Destroy_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Pub_Destroy(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_SetDescription_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, _gostring_ _swig_go_1, intgo _swig_go_2) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  char *arg2 = (char *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  arg3 = (int)_swig_go_2; 
  
  result = (int)eCAL_Pub_SetDescription(arg1,(char const *)arg2,arg3);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_ShareType_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, intgo _swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)eCAL_Pub_ShareType(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_ShareDescription_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, intgo _swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)eCAL_Pub_ShareDescription(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_SetQOS_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, struct SWriterQOSC *_swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  struct SWriterQOSC arg2 ;
  struct SWriterQOSC *argp2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  argp2 = (struct SWriterQOSC *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null struct SWriterQOSC");
  }
  arg2 = (struct SWriterQOSC)*argp2;
  
  
  result = (int)eCAL_Pub_SetQOS(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_GetQOS_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, struct SWriterQOSC *_swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  struct SWriterQOSC *arg2 = (struct SWriterQOSC *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(struct SWriterQOSC **)&_swig_go_1; 
  
  result = (int)eCAL_Pub_GetQOS(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_SetLayerMode_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  enum eTransportLayerC arg2 ;
  enum eSendModeC arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (enum eTransportLayerC)_swig_go_1; 
  arg3 = (enum eSendModeC)_swig_go_2; 
  
  result = (int)eCAL_Pub_SetLayerMode(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_SetMaxBandwidthUDP_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, long long _swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  long arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (long)_swig_go_1; 
  
  result = (int)eCAL_Pub_SetMaxBandwidthUDP(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_SetID_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, long long _swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  long long arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (long long)_swig_go_1; 
  
  result = (int)eCAL_Pub_SetID(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_IsSubscribed_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Pub_IsSubscribed(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_Send_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, void *_swig_go_1, intgo _swig_go_2, long long _swig_go_3) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  void *arg2 = (void *) (void *)0 ;
  int arg3 ;
  long long arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (long long)_swig_go_3; 
  
  result = (int)eCAL_Pub_Send(arg1,(void const *)arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_AddEventCallbackC_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, intgo _swig_go_1, void* _swig_go_2, void *_swig_go_3) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  enum eCAL_Publisher_Event arg2 ;
  PubEventCallbackCT arg3 = (PubEventCallbackCT) 0 ;
  void *arg4 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (enum eCAL_Publisher_Event)_swig_go_1; 
  arg3 = *(PubEventCallbackCT *)&_swig_go_2; 
  arg4 = *(void **)&_swig_go_3; 
  
  result = (int)eCAL_Pub_AddEventCallbackC(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_RemEventCallback_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, intgo _swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  enum eCAL_Publisher_Event arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (enum eCAL_Publisher_Event)_swig_go_1; 
  
  result = (int)eCAL_Pub_RemEventCallback(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Pub_Dump_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, void *_swig_go_1, intgo _swig_go_2) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)eCAL_Pub_Dump(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_keep_last_history_qos_ecalc_5c8096034791d065() {
  enum eQOSPolicy_HistoryKindC result;
  intgo _swig_go_result;
  
  
  result = keep_last_history_qos;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_keep_all_history_qos_ecalc_5c8096034791d065() {
  enum eQOSPolicy_HistoryKindC result;
  intgo _swig_go_result;
  
  
  result = keep_all_history_qos;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_best_effort_reliability_qos_ecalc_5c8096034791d065() {
  enum eQOSPolicy_ReliabilityC result;
  intgo _swig_go_result;
  
  
  result = best_effort_reliability_qos;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_reliable_reliability_qos_ecalc_5c8096034791d065() {
  enum eQOSPolicy_ReliabilityC result;
  intgo _swig_go_result;
  
  
  result = reliable_reliability_qos;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_SWriterQOSC_history_kind_set_ecalc_5c8096034791d065(struct SWriterQOSC *_swig_go_0, intgo _swig_go_1) {
  struct SWriterQOSC *arg1 = (struct SWriterQOSC *) 0 ;
  enum eQOSPolicy_HistoryKindC arg2 ;
  
  arg1 = *(struct SWriterQOSC **)&_swig_go_0; 
  arg2 = (enum eQOSPolicy_HistoryKindC)_swig_go_1; 
  
  if (arg1) (arg1)->history_kind = arg2;
  
}


intgo _wrap_SWriterQOSC_history_kind_get_ecalc_5c8096034791d065(struct SWriterQOSC *_swig_go_0) {
  struct SWriterQOSC *arg1 = (struct SWriterQOSC *) 0 ;
  enum eQOSPolicy_HistoryKindC result;
  intgo _swig_go_result;
  
  arg1 = *(struct SWriterQOSC **)&_swig_go_0; 
  
  result = (enum eQOSPolicy_HistoryKindC) ((arg1)->history_kind);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_SWriterQOSC_history_kind_depth_set_ecalc_5c8096034791d065(struct SWriterQOSC *_swig_go_0, intgo _swig_go_1) {
  struct SWriterQOSC *arg1 = (struct SWriterQOSC *) 0 ;
  int arg2 ;
  
  arg1 = *(struct SWriterQOSC **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->history_kind_depth = arg2;
  
}


intgo _wrap_SWriterQOSC_history_kind_depth_get_ecalc_5c8096034791d065(struct SWriterQOSC *_swig_go_0) {
  struct SWriterQOSC *arg1 = (struct SWriterQOSC *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct SWriterQOSC **)&_swig_go_0; 
  
  result = (int) ((arg1)->history_kind_depth);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SWriterQOSC_reliability_set_ecalc_5c8096034791d065(struct SWriterQOSC *_swig_go_0, intgo _swig_go_1) {
  struct SWriterQOSC *arg1 = (struct SWriterQOSC *) 0 ;
  enum eQOSPolicy_ReliabilityC arg2 ;
  
  arg1 = *(struct SWriterQOSC **)&_swig_go_0; 
  arg2 = (enum eQOSPolicy_ReliabilityC)_swig_go_1; 
  
  if (arg1) (arg1)->reliability = arg2;
  
}


intgo _wrap_SWriterQOSC_reliability_get_ecalc_5c8096034791d065(struct SWriterQOSC *_swig_go_0) {
  struct SWriterQOSC *arg1 = (struct SWriterQOSC *) 0 ;
  enum eQOSPolicy_ReliabilityC result;
  intgo _swig_go_result;
  
  arg1 = *(struct SWriterQOSC **)&_swig_go_0; 
  
  result = (enum eQOSPolicy_ReliabilityC) ((arg1)->reliability);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


struct SWriterQOSC *_wrap_new_SWriterQOSC_ecalc_5c8096034791d065() {
  struct SWriterQOSC *result = 0 ;
  struct SWriterQOSC *_swig_go_result;
  
  
  result = (struct SWriterQOSC *)calloc(1, sizeof(struct SWriterQOSC));
  *(struct SWriterQOSC **)&_swig_go_result = (struct SWriterQOSC *)result; 
  return _swig_go_result;
}


void _wrap_delete_SWriterQOSC_ecalc_5c8096034791d065(struct SWriterQOSC *_swig_go_0) {
  struct SWriterQOSC *arg1 = (struct SWriterQOSC *) 0 ;
  
  arg1 = *(struct SWriterQOSC **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void _wrap_SReaderQOSC_history_kind_set_ecalc_5c8096034791d065(struct SReaderQOSC *_swig_go_0, intgo _swig_go_1) {
  struct SReaderQOSC *arg1 = (struct SReaderQOSC *) 0 ;
  enum eQOSPolicy_HistoryKindC arg2 ;
  
  arg1 = *(struct SReaderQOSC **)&_swig_go_0; 
  arg2 = (enum eQOSPolicy_HistoryKindC)_swig_go_1; 
  
  if (arg1) (arg1)->history_kind = arg2;
  
}


intgo _wrap_SReaderQOSC_history_kind_get_ecalc_5c8096034791d065(struct SReaderQOSC *_swig_go_0) {
  struct SReaderQOSC *arg1 = (struct SReaderQOSC *) 0 ;
  enum eQOSPolicy_HistoryKindC result;
  intgo _swig_go_result;
  
  arg1 = *(struct SReaderQOSC **)&_swig_go_0; 
  
  result = (enum eQOSPolicy_HistoryKindC) ((arg1)->history_kind);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_SReaderQOSC_history_kind_depth_set_ecalc_5c8096034791d065(struct SReaderQOSC *_swig_go_0, intgo _swig_go_1) {
  struct SReaderQOSC *arg1 = (struct SReaderQOSC *) 0 ;
  int arg2 ;
  
  arg1 = *(struct SReaderQOSC **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->history_kind_depth = arg2;
  
}


intgo _wrap_SReaderQOSC_history_kind_depth_get_ecalc_5c8096034791d065(struct SReaderQOSC *_swig_go_0) {
  struct SReaderQOSC *arg1 = (struct SReaderQOSC *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(struct SReaderQOSC **)&_swig_go_0; 
  
  result = (int) ((arg1)->history_kind_depth);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_SReaderQOSC_reliability_set_ecalc_5c8096034791d065(struct SReaderQOSC *_swig_go_0, intgo _swig_go_1) {
  struct SReaderQOSC *arg1 = (struct SReaderQOSC *) 0 ;
  enum eQOSPolicy_ReliabilityC arg2 ;
  
  arg1 = *(struct SReaderQOSC **)&_swig_go_0; 
  arg2 = (enum eQOSPolicy_ReliabilityC)_swig_go_1; 
  
  if (arg1) (arg1)->reliability = arg2;
  
}


intgo _wrap_SReaderQOSC_reliability_get_ecalc_5c8096034791d065(struct SReaderQOSC *_swig_go_0) {
  struct SReaderQOSC *arg1 = (struct SReaderQOSC *) 0 ;
  enum eQOSPolicy_ReliabilityC result;
  intgo _swig_go_result;
  
  arg1 = *(struct SReaderQOSC **)&_swig_go_0; 
  
  result = (enum eQOSPolicy_ReliabilityC) ((arg1)->reliability);
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


struct SReaderQOSC *_wrap_new_SReaderQOSC_ecalc_5c8096034791d065() {
  struct SReaderQOSC *result = 0 ;
  struct SReaderQOSC *_swig_go_result;
  
  
  result = (struct SReaderQOSC *)calloc(1, sizeof(struct SReaderQOSC));
  *(struct SReaderQOSC **)&_swig_go_result = (struct SReaderQOSC *)result; 
  return _swig_go_result;
}


void _wrap_delete_SReaderQOSC_ecalc_5c8096034791d065(struct SReaderQOSC *_swig_go_0) {
  struct SReaderQOSC *arg1 = (struct SReaderQOSC *) 0 ;
  
  arg1 = *(struct SReaderQOSC **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


ECAL_HANDLE _wrap_eCAL_Server_Create_ecalc_5c8096034791d065(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  ECAL_HANDLE result;
  ECAL_HANDLE _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (ECAL_HANDLE)eCAL_Server_Create((char const *)arg1);
  *(ECAL_HANDLE *)&_swig_go_result = (ECAL_HANDLE)result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Server_Destroy_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Server_Destroy(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Server_AddMethodCallbackC_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, _gostring_ _swig_go_3, MethodCallbackCT *_swig_go_4, void *_swig_go_5) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  MethodCallbackCT arg5 ;
  void *arg6 = (void *) 0 ;
  MethodCallbackCT *argp5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  
  argp5 = (MethodCallbackCT *)_swig_go_4;
  if (argp5 == NULL) {
    _swig_gopanic("Attempt to dereference null MethodCallbackCT");
  }
  arg5 = (MethodCallbackCT)*argp5;
  
  arg6 = *(void **)&_swig_go_5; 
  
  result = (int)eCAL_Server_AddMethodCallbackC(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,arg5,arg6);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  free(arg4); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Server_RemMethodCallbackC_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, _gostring_ _swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)eCAL_Server_RemMethodCallbackC(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Server_GetServiceName_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, void *_swig_go_1, intgo _swig_go_2) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)eCAL_Server_GetServiceName(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


ECAL_HANDLE _wrap_eCAL_Client_Create_ecalc_5c8096034791d065(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  ECAL_HANDLE result;
  ECAL_HANDLE _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (ECAL_HANDLE)eCAL_Client_Create((char const *)arg1);
  *(ECAL_HANDLE *)&_swig_go_result = (ECAL_HANDLE)result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Client_Destroy_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Client_Destroy(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Client_SetHostName_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, _gostring_ _swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  result = (int)eCAL_Client_SetHostName(arg1,(char const *)arg2);
  _swig_go_result = result; 
  free(arg2); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Client_Call_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, intgo _swig_go_3) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (int)_swig_go_3; 
  
  result = (int)eCAL_Client_Call(arg1,(char const *)arg2,(char const *)arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Client_Call_Wait_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, _gostring_ _swig_go_3, intgo _swig_go_4, struct SServiceInfoC *_swig_go_5, void *_swig_go_6, intgo _swig_go_7) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int arg5 ;
  struct SServiceInfoC *arg6 = (struct SServiceInfoC *) 0 ;
  void *arg7 = (void *) 0 ;
  int arg8 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  arg5 = (int)_swig_go_4; 
  arg6 = *(struct SServiceInfoC **)&_swig_go_5; 
  arg7 = *(void **)&_swig_go_6; 
  arg8 = (int)_swig_go_7; 
  
  result = (int)eCAL_Client_Call_Wait(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,arg5,arg6,arg7,arg8);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  free(arg4); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Client_AddResponseCallbackC_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, ResponseCallbackCT *_swig_go_1, void *_swig_go_2) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  ResponseCallbackCT arg2 ;
  void *arg3 = (void *) 0 ;
  ResponseCallbackCT *argp2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  argp2 = (ResponseCallbackCT *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null ResponseCallbackCT");
  }
  arg2 = (ResponseCallbackCT)*argp2;
  
  arg3 = *(void **)&_swig_go_2; 
  
  result = (int)eCAL_Client_AddResponseCallbackC(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Client_RemResponseCallback_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Client_RemResponseCallback(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


ECAL_HANDLE _wrap_eCAL_Sub_New_ecalc_5c8096034791d065() {
  ECAL_HANDLE result;
  ECAL_HANDLE _swig_go_result;
  
  
  result = (ECAL_HANDLE)eCAL_Sub_New();
  *(ECAL_HANDLE *)&_swig_go_result = (ECAL_HANDLE)result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_Create_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, _gostring_ _swig_go_3, intgo _swig_go_4) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  char *arg4 = (char *) 0 ;
  int arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  arg4 = (char *)malloc(_swig_go_3.n + 1);
  memcpy(arg4, _swig_go_3.p, _swig_go_3.n);
  arg4[_swig_go_3.n] = '\0';
  
  arg5 = (int)_swig_go_4; 
  
  result = (int)eCAL_Sub_Create(arg1,(char const *)arg2,(char const *)arg3,(char const *)arg4,arg5);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  free(arg4); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_Destroy_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Sub_Destroy(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_SetQOS_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, struct SReaderQOSC *_swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  struct SReaderQOSC arg2 ;
  struct SReaderQOSC *argp2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  argp2 = (struct SReaderQOSC *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null struct SReaderQOSC");
  }
  arg2 = (struct SReaderQOSC)*argp2;
  
  
  result = (int)eCAL_Sub_SetQOS(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_GetQOS_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, struct SReaderQOSC *_swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  struct SReaderQOSC *arg2 = (struct SReaderQOSC *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(struct SReaderQOSC **)&_swig_go_1; 
  
  result = (int)eCAL_Sub_GetQOS(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_SetID_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, long long *_swig_go_1, intgo _swig_go_2) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  long long *arg2 = (long long *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(long long **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)eCAL_Sub_SetID(arg1,(long long const *)arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_Receive_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, void *_swig_go_1, intgo _swig_go_2, long long *_swig_go_3, intgo _swig_go_4) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  long long *arg4 = (long long *) 0 ;
  int arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = *(long long **)&_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  
  result = (int)eCAL_Sub_Receive(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_Receive_ToBuffer_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, void *_swig_go_1, intgo _swig_go_2, long long *_swig_go_3, intgo _swig_go_4) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  long long *arg4 = (long long *) 0 ;
  int arg5 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = *(long long **)&_swig_go_3; 
  arg5 = (int)_swig_go_4; 
  
  result = (int)eCAL_Sub_Receive_ToBuffer(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_Receive_Alloc_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, void **_swig_go_1, long long *_swig_go_2, intgo _swig_go_3) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  void **arg2 = (void **) 0 ;
  long long *arg3 = (long long *) 0 ;
  int arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(void ***)&_swig_go_1; 
  arg3 = *(long long **)&_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  
  result = (int)eCAL_Sub_Receive_Alloc(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_AddReceiveCallbackC_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, void* _swig_go_1, void *_swig_go_2) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  ReceiveCallbackCT arg2 = (ReceiveCallbackCT) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(ReceiveCallbackCT *)&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  result = (int)eCAL_Sub_AddReceiveCallbackC(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_RemReceiveCallback_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Sub_RemReceiveCallback(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_AddEventCallbackC_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, intgo _swig_go_1, void* _swig_go_2, void *_swig_go_3) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  enum eCAL_Subscriber_Event arg2 ;
  SubEventCallbackCT arg3 = (SubEventCallbackCT) 0 ;
  void *arg4 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (enum eCAL_Subscriber_Event)_swig_go_1; 
  arg3 = *(SubEventCallbackCT *)&_swig_go_2; 
  arg4 = *(void **)&_swig_go_3; 
  
  result = (int)eCAL_Sub_AddEventCallbackC(arg1,arg2,arg3,arg4);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_RemEventCallback_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, intgo _swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  enum eCAL_Subscriber_Event arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (enum eCAL_Subscriber_Event)_swig_go_1; 
  
  result = (int)eCAL_Sub_RemEventCallback(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_GetDescription_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, void *_swig_go_1, intgo _swig_go_2) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)eCAL_Sub_GetDescription(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_SetTimeout_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, intgo _swig_go_1) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)eCAL_Sub_SetTimeout(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Sub_Dump_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, void *_swig_go_1, intgo _swig_go_2) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)eCAL_Sub_Dump(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


ECAL_HANDLE _wrap_eCAL_Proto_Dyn_JSON_Sub_Create_ecalc_5c8096034791d065(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  ECAL_HANDLE result;
  ECAL_HANDLE _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  result = (ECAL_HANDLE)eCAL_Proto_Dyn_JSON_Sub_Create((char const *)arg1);
  *(ECAL_HANDLE *)&_swig_go_result = (ECAL_HANDLE)result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Proto_Dyn_JSON_Sub_Destroy_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Proto_Dyn_JSON_Sub_Destroy(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Proto_Dyn_JSON_Sub_AddReceiveCallbackC_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, void* _swig_go_1, void *_swig_go_2) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  ReceiveCallbackCT arg2 = (ReceiveCallbackCT) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = *(ReceiveCallbackCT *)&_swig_go_1; 
  arg3 = *(void **)&_swig_go_2; 
  
  result = (int)eCAL_Proto_Dyn_JSON_Sub_AddReceiveCallbackC(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Proto_Dyn_JSON_Sub_RemReceiveCallback_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Proto_Dyn_JSON_Sub_RemReceiveCallback(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Time_GetName_ecalc_5c8096034791d065(void *_swig_go_0, intgo _swig_go_1) {
  void *arg1 = (void *) 0 ;
  int arg2 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(void **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (int)eCAL_Time_GetName(arg1,arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_eCAL_Time_GetMicroSeconds_ecalc_5c8096034791d065() {
  long long result;
  long long _swig_go_result;
  
  
  result = (long long)eCAL_Time_GetMicroSeconds();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_eCAL_Time_GetNanoSeconds_ecalc_5c8096034791d065() {
  long long result;
  long long _swig_go_result;
  
  
  result = (long long)eCAL_Time_GetNanoSeconds();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Time_SetNanoSeconds_ecalc_5c8096034791d065(long long _swig_go_0) {
  long long arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (long long)_swig_go_0; 
  
  result = (int)eCAL_Time_SetNanoSeconds(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Time_IsTimeSynchronized_ecalc_5c8096034791d065() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)eCAL_Time_IsTimeSynchronized();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Time_IsTimeMaster_ecalc_5c8096034791d065() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)eCAL_Time_IsTimeMaster();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_eCAL_Time_SleepForNanoseconds_ecalc_5c8096034791d065(long long _swig_go_0) {
  long long arg1 ;
  
  arg1 = (long long)_swig_go_0; 
  
  eCAL_Time_SleepForNanoseconds(arg1);
  
}


intgo _wrap_eCAL_Time_GetStatus_ecalc_5c8096034791d065(intgo *_swig_go_0, _gostring_* _swig_go_1, intgo _swig_go_2) {
  int *arg1 = (int *) 0 ;
  char **arg2 = (char **) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(int **)&_swig_go_0; 
  arg2 = *(char ***)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)eCAL_Time_GetStatus(arg1,arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


ECAL_HANDLE _wrap_eCAL_Timer_Create_ecalc_5c8096034791d065() {
  ECAL_HANDLE result;
  ECAL_HANDLE _swig_go_result;
  
  
  result = (ECAL_HANDLE)eCAL_Timer_Create();
  *(ECAL_HANDLE *)&_swig_go_result = (ECAL_HANDLE)result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Timer_Destroy_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Timer_Destroy(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Timer_Start_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0, intgo _swig_go_1, void* _swig_go_2, intgo _swig_go_3, void *_swig_go_4) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int arg2 ;
  TimerCallbackCT arg3 = (TimerCallbackCT) 0 ;
  int arg4 ;
  void *arg5 = (void *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(TimerCallbackCT *)&_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(void **)&_swig_go_4; 
  
  result = (int)eCAL_Timer_Start(arg1,arg2,arg3,arg4,arg5);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_eCAL_Timer_Stop_ecalc_5c8096034791d065(ECAL_HANDLE _swig_go_0) {
  ECAL_HANDLE arg1 = (ECAL_HANDLE) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(ECAL_HANDLE *)&_swig_go_0; 
  
  result = (int)eCAL_Timer_Stop(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_tlayer_none_ecalc_5c8096034791d065() {
  enum eTransportLayerC result;
  intgo _swig_go_result;
  
  
  result = tlayer_none;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_tlayer_udp_mc_ecalc_5c8096034791d065() {
  enum eTransportLayerC result;
  intgo _swig_go_result;
  
  
  result = tlayer_udp_mc;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_tlayer_shm_ecalc_5c8096034791d065() {
  enum eTransportLayerC result;
  intgo _swig_go_result;
  
  
  result = tlayer_shm;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_tlayer_inproc_ecalc_5c8096034791d065() {
  enum eTransportLayerC result;
  intgo _swig_go_result;
  
  
  result = tlayer_inproc;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_tlayer_all_ecalc_5c8096034791d065() {
  enum eTransportLayerC result;
  intgo _swig_go_result;
  
  
  result = tlayer_all;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_smode_none_ecalc_5c8096034791d065() {
  enum eSendModeC result;
  intgo _swig_go_result;
  
  
  result = smode_none;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_smode_off_ecalc_5c8096034791d065() {
  enum eSendModeC result;
  intgo _swig_go_result;
  
  
  result = smode_off;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_smode_on_ecalc_5c8096034791d065() {
  enum eSendModeC result;
  intgo _swig_go_result;
  
  
  result = smode_on;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_smode_auto_ecalc_5c8096034791d065() {
  enum eSendModeC result;
  intgo _swig_go_result;
  
  
  result = smode_auto;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_eCAL_Util_ShutdownUnitName_ecalc_5c8096034791d065(_gostring_ _swig_go_0) {
  char *arg1 = (char *) 0 ;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  
  eCAL_Util_ShutdownUnitName((char const *)arg1);
  
  free(arg1); 
}


void _wrap_eCAL_Util_ShutdownProcessID_ecalc_5c8096034791d065(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  eCAL_Util_ShutdownProcessID(arg1);
  
}


void _wrap_eCAL_Util_ShutdownProcesses_ecalc_5c8096034791d065() {
  eCAL_Util_ShutdownProcesses();
  
}


void _wrap_eCAL_Util_ShutdownCore_ecalc_5c8096034791d065() {
  eCAL_Util_ShutdownCore();
  
}


void _wrap_eCAL_Util_EnableLoopback_ecalc_5c8096034791d065(intgo _swig_go_0) {
  int arg1 ;
  
  arg1 = (int)_swig_go_0; 
  
  eCAL_Util_EnableLoopback(arg1);
  
}


intgo _wrap_eCAL_Util_GetTypeName_ecalc_5c8096034791d065(_gostring_ _swig_go_0, void *_swig_go_1, intgo _swig_go_2) {
  char *arg1 = (char *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)eCAL_Util_GetTypeName((char const *)arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


intgo _wrap_eCAL_Util_GetDescription_ecalc_5c8096034791d065(_gostring_ _swig_go_0, void *_swig_go_1, intgo _swig_go_2) {
  char *arg1 = (char *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  int result;
  intgo _swig_go_result;
  
  
  arg1 = (char *)malloc(_swig_go_0.n + 1);
  memcpy(arg1, _swig_go_0.p, _swig_go_0.n);
  arg1[_swig_go_0.n] = '\0';
  
  arg2 = *(void **)&_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (int)eCAL_Util_GetDescription((char const *)arg1,arg2,arg3);
  _swig_go_result = result; 
  free(arg1); 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

