/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: golang-ecalc.i

package ecalc

/*
#cgo LDFLAGS: -lecal_core_c
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef long long swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef long long swig_type_20;
typedef long long swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef _gostring_ swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef _gostring_ swig_type_29;
typedef _gostring_ swig_type_30;
typedef long long swig_type_31;
typedef long long swig_type_32;
typedef long long swig_type_33;
typedef _gostring_ swig_type_34;
typedef _gostring_ swig_type_35;
typedef _gostring_ swig_type_36;
typedef _gostring_ swig_type_37;
typedef _gostring_ swig_type_38;
typedef _gostring_ swig_type_39;
typedef _gostring_ swig_type_40;
typedef _gostring_ swig_type_41;
typedef _gostring_ swig_type_42;
typedef _gostring_ swig_type_43;
typedef _gostring_ swig_type_44;
typedef _gostring_ swig_type_45;
typedef _gostring_ swig_type_46;
typedef _gostring_ swig_type_47;
typedef _gostring_ swig_type_48;
typedef _gostring_ swig_type_49;
typedef long long swig_type_50;
typedef long long swig_type_51;
typedef long long swig_type_52;
typedef long long swig_type_53;
typedef _gostring_ swig_type_54;
typedef _gostring_ swig_type_55;
typedef _gostring_ swig_type_56;
extern void _wrap_Swig_free_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_swig_cd49d5ad85cbb53a(swig_intgo arg1);
extern swig_intgo _wrap_ECAL_VERSION_MAJOR_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_ECAL_VERSION_MINOR_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_ECAL_VERSION_PATCH_swig_cd49d5ad85cbb53a(void);
extern swig_type_1 _wrap_ECAL_PLATFORMTOOLSET_swig_cd49d5ad85cbb53a(void);
extern swig_type_2 _wrap_eCAL_GetVersionString_swig_cd49d5ad85cbb53a(void);
extern swig_type_3 _wrap_eCAL_GetVersionDateString_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_GetVersion_swig_cd49d5ad85cbb53a(swig_voidp arg1, swig_voidp arg2, swig_voidp arg3);
extern swig_intgo _wrap_eCAL_Initialize_swig_cd49d5ad85cbb53a(swig_intgo arg1, swig_voidp arg2, swig_type_4 arg3, swig_intgo arg4);
extern swig_intgo _wrap_eCAL_SetUnitName_swig_cd49d5ad85cbb53a(swig_type_5 arg1);
extern swig_intgo _wrap_eCAL_Finalize_swig_cd49d5ad85cbb53a(swig_intgo arg1);
extern swig_intgo _wrap_eCAL_IsInitialized_swig_cd49d5ad85cbb53a(swig_intgo arg1);
extern swig_intgo _wrap_eCAL_Ok_swig_cd49d5ad85cbb53a(void);
extern void _wrap_eCAL_FreeMem_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern uintptr_t _wrap_eCAL_Event_gOpenEvent_swig_cd49d5ad85cbb53a(swig_type_6 arg1);
extern swig_intgo _wrap_eCAL_Event_gCloseEvent_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Event_gSetEvent_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Event_gWaitForEvent_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_7 arg2);
extern swig_intgo _wrap_eCAL_Event_gEventIsValid_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Init_All_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_Init_Default_swig_cd49d5ad85cbb53a(void);
extern void _wrap_eCAL_Logging_SetLogLevel_swig_cd49d5ad85cbb53a(swig_intgo arg1);
extern swig_intgo _wrap_eCAL_Logging_GetLogLevel_swig_cd49d5ad85cbb53a(void);
extern void _wrap_eCAL_Logging_Log_swig_cd49d5ad85cbb53a(swig_type_8 arg1);
extern void _wrap_eCAL_Logging_StartCoreTimer_swig_cd49d5ad85cbb53a(void);
extern void _wrap_eCAL_Logging_StopCoreTimer_swig_cd49d5ad85cbb53a(void);
extern void _wrap_eCAL_Logging_SetCoreTime_swig_cd49d5ad85cbb53a(double arg1);
extern double _wrap_eCAL_Logging_GetCoreTime_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_Monitoring_SetExclFilter_swig_cd49d5ad85cbb53a(swig_type_9 arg1);
extern swig_intgo _wrap_eCAL_Monitoring_SetInclFilter_swig_cd49d5ad85cbb53a(swig_type_10 arg1);
extern swig_intgo _wrap_eCAL_Monitoring_SetFilterState_swig_cd49d5ad85cbb53a(swig_intgo arg1);
extern swig_intgo _wrap_eCAL_Monitoring_GetMonitoring_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_eCAL_Monitoring_GetLogging_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_eCAL_Monitoring_PubMonitoring_swig_cd49d5ad85cbb53a(swig_intgo arg1, swig_type_11 arg2);
extern swig_intgo _wrap_eCAL_Monitoring_PubLogging_swig_cd49d5ad85cbb53a(swig_intgo arg1, swig_type_12 arg2);
extern void _wrap_eCAL_Process_DumpConfig_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_Process_GetHostName_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_eCAL_Process_GetHostID_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_Process_GetUnitName_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_eCAL_Process_GetTaskParameter_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2, swig_type_13 arg3);
extern void _wrap_eCAL_Process_SleepMS_swig_cd49d5ad85cbb53a(swig_type_14 arg1);
extern swig_intgo _wrap_eCAL_Process_GetProcessID_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_Process_GetProcessName_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_eCAL_Process_GetProcessParameter_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern float _wrap_eCAL_Process_GetProcessCpuUsage_swig_cd49d5ad85cbb53a(void);
extern swig_type_15 _wrap_eCAL_Process_GetProcessMemory_swig_cd49d5ad85cbb53a(void);
extern swig_type_16 _wrap_eCAL_Process_GetSClock_swig_cd49d5ad85cbb53a(void);
extern swig_type_17 _wrap_eCAL_Process_GetSBytes_swig_cd49d5ad85cbb53a(void);
extern swig_type_18 _wrap_eCAL_Process_GetWClock_swig_cd49d5ad85cbb53a(void);
extern swig_type_19 _wrap_eCAL_Process_GetWBytes_swig_cd49d5ad85cbb53a(void);
extern swig_type_20 _wrap_eCAL_Process_GetRClock_swig_cd49d5ad85cbb53a(void);
extern swig_type_21 _wrap_eCAL_Process_GetRBytes_swig_cd49d5ad85cbb53a(void);
extern void _wrap_eCAL_Process_SetState_swig_cd49d5ad85cbb53a(swig_intgo arg1, swig_intgo arg2, swig_type_22 arg3);
extern swig_intgo _wrap_eCAL_Process_StartProcess_swig_cd49d5ad85cbb53a(swig_type_23 arg1, swig_type_24 arg2, swig_type_25 arg3, swig_intgo arg4, swig_intgo arg5, swig_intgo arg6);
extern swig_intgo _wrap_eCAL_Process_StopProcessName_swig_cd49d5ad85cbb53a(swig_type_26 arg1);
extern swig_intgo _wrap_eCAL_Process_StopProcessID_swig_cd49d5ad85cbb53a(swig_intgo arg1);
extern uintptr_t _wrap_eCAL_Pub_New_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_Pub_Create_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_27 arg2, swig_type_28 arg3, swig_type_29 arg4, swig_intgo arg5);
extern swig_intgo _wrap_eCAL_Pub_Destroy_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Pub_SetDescription_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_30 arg2, swig_intgo arg3);
extern swig_intgo _wrap_eCAL_Pub_ShareType_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_eCAL_Pub_ShareDescription_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_eCAL_Pub_SetQOS_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_eCAL_Pub_GetQOS_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_eCAL_Pub_SetLayerMode_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3);
extern swig_intgo _wrap_eCAL_Pub_SetMaxBandwidthUDP_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_31 arg2);
extern swig_intgo _wrap_eCAL_Pub_SetID_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_32 arg2);
extern swig_intgo _wrap_eCAL_Pub_IsSubscribed_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Pub_Send_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3, swig_type_33 arg4);
extern swig_intgo _wrap_eCAL_Pub_AddEventCallbackC_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2, uintptr_t arg3, uintptr_t arg4);
extern swig_intgo _wrap_eCAL_Pub_RemEventCallback_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_eCAL_Pub_Dump_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern swig_intgo _wrap_keep_last_history_qos_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_keep_all_history_qos_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_best_effort_reliability_qos_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_reliable_reliability_qos_swig_cd49d5ad85cbb53a(void);
extern void _wrap_SWriterQOSC_history_kind_set_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_SWriterQOSC_history_kind_get_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern void _wrap_SWriterQOSC_history_kind_depth_set_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_SWriterQOSC_history_kind_depth_get_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern void _wrap_SWriterQOSC_reliability_set_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_SWriterQOSC_reliability_get_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern uintptr_t _wrap_new_SWriterQOSC_swig_cd49d5ad85cbb53a(void);
extern void _wrap_delete_SWriterQOSC_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern void _wrap_SReaderQOSC_history_kind_set_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_SReaderQOSC_history_kind_get_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern void _wrap_SReaderQOSC_history_kind_depth_set_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_SReaderQOSC_history_kind_depth_get_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern void _wrap_SReaderQOSC_reliability_set_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_SReaderQOSC_reliability_get_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern uintptr_t _wrap_new_SReaderQOSC_swig_cd49d5ad85cbb53a(void);
extern void _wrap_delete_SReaderQOSC_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern uintptr_t _wrap_eCAL_Server_Create_swig_cd49d5ad85cbb53a(swig_type_34 arg1);
extern swig_intgo _wrap_eCAL_Server_Destroy_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Server_AddMethodCallbackC_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_35 arg2, swig_type_36 arg3, swig_type_37 arg4, uintptr_t arg5, uintptr_t arg6);
extern swig_intgo _wrap_eCAL_Server_RemMethodCallbackC_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_38 arg2);
extern swig_intgo _wrap_eCAL_Server_GetServiceName_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern uintptr_t _wrap_eCAL_Client_Create_swig_cd49d5ad85cbb53a(swig_type_39 arg1);
extern swig_intgo _wrap_eCAL_Client_Destroy_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Client_SetHostName_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_40 arg2);
extern swig_intgo _wrap_eCAL_Client_Call_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_41 arg2, swig_type_42 arg3, swig_intgo arg4);
extern swig_intgo _wrap_eCAL_Client_Call_Wait_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_43 arg2, swig_type_44 arg3, swig_type_45 arg4, swig_intgo arg5, uintptr_t arg6, uintptr_t arg7, swig_intgo arg8);
extern swig_intgo _wrap_eCAL_Client_AddResponseCallbackC_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_eCAL_Client_RemResponseCallback_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern uintptr_t _wrap_eCAL_Sub_New_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_Sub_Create_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_type_46 arg2, swig_type_47 arg3, swig_type_48 arg4, swig_intgo arg5);
extern swig_intgo _wrap_eCAL_Sub_Destroy_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Sub_SetQOS_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_eCAL_Sub_GetQOS_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2);
extern swig_intgo _wrap_eCAL_Sub_SetID_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_voidp arg2, swig_intgo arg3);
extern swig_intgo _wrap_eCAL_Sub_Receive_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3, swig_voidp arg4, swig_intgo arg5);
extern swig_intgo _wrap_eCAL_Sub_AddReceiveCallbackC_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_eCAL_Sub_RemReceiveCallback_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Sub_AddEventCallbackC_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2, uintptr_t arg3, uintptr_t arg4);
extern swig_intgo _wrap_eCAL_Sub_RemEventCallback_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_eCAL_Sub_GetDescription_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern swig_intgo _wrap_eCAL_Sub_SetTimeout_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_eCAL_Sub_Dump_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2, swig_intgo arg3);
extern uintptr_t _wrap_eCAL_Proto_Dyn_JSON_Sub_Create_swig_cd49d5ad85cbb53a(swig_type_49 arg1);
extern swig_intgo _wrap_eCAL_Proto_Dyn_JSON_Sub_Destroy_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Proto_Dyn_JSON_Sub_AddReceiveCallbackC_swig_cd49d5ad85cbb53a(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern swig_intgo _wrap_eCAL_Proto_Dyn_JSON_Sub_RemReceiveCallback_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Time_GetName_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2);
extern swig_type_50 _wrap_eCAL_Time_GetMicroSeconds_swig_cd49d5ad85cbb53a(void);
extern swig_type_51 _wrap_eCAL_Time_GetNanoSeconds_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_Time_SetNanoSeconds_swig_cd49d5ad85cbb53a(swig_type_52 arg1);
extern swig_intgo _wrap_eCAL_Time_IsTimeSynchronized_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_Time_IsTimeMaster_swig_cd49d5ad85cbb53a(void);
extern void _wrap_eCAL_Time_SleepForNanoseconds_swig_cd49d5ad85cbb53a(swig_type_53 arg1);
extern swig_intgo _wrap_eCAL_Time_GetStatus_swig_cd49d5ad85cbb53a(swig_voidp arg1, swig_voidp arg2, swig_intgo arg3);
extern uintptr_t _wrap_eCAL_Timer_Create_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_eCAL_Timer_Destroy_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_eCAL_Timer_Start_swig_cd49d5ad85cbb53a(uintptr_t arg1, swig_intgo arg2, uintptr_t arg3, swig_intgo arg4, uintptr_t arg5);
extern swig_intgo _wrap_eCAL_Timer_Stop_swig_cd49d5ad85cbb53a(uintptr_t arg1);
extern swig_intgo _wrap_tlayer_none_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_tlayer_udp_mc_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_tlayer_shm_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_tlayer_inproc_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_tlayer_all_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_smode_none_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_smode_off_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_smode_on_swig_cd49d5ad85cbb53a(void);
extern swig_intgo _wrap_smode_auto_swig_cd49d5ad85cbb53a(void);
extern void _wrap_eCAL_Util_ShutdownUnitName_swig_cd49d5ad85cbb53a(swig_type_54 arg1);
extern void _wrap_eCAL_Util_ShutdownProcessID_swig_cd49d5ad85cbb53a(swig_intgo arg1);
extern void _wrap_eCAL_Util_ShutdownProcesses_swig_cd49d5ad85cbb53a(void);
extern void _wrap_eCAL_Util_ShutdownCore_swig_cd49d5ad85cbb53a(void);
extern void _wrap_eCAL_Util_EnableLoopback_swig_cd49d5ad85cbb53a(swig_intgo arg1);
extern swig_intgo _wrap_eCAL_Util_GetTypeName_swig_cd49d5ad85cbb53a(swig_type_55 arg1, uintptr_t arg2, swig_intgo arg3);
extern swig_intgo _wrap_eCAL_Util_GetDescription_swig_cd49d5ad85cbb53a(swig_type_56 arg1, uintptr_t arg2, swig_intgo arg3);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0)))
	return swig_r
}

const ECAL_ALLOCATE_4ME int = 0
func _swig_getECAL_VERSION_MAJOR() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_ECAL_VERSION_MAJOR_swig_cd49d5ad85cbb53a())
	return swig_r
}

var ECAL_VERSION_MAJOR int = _swig_getECAL_VERSION_MAJOR()
func _swig_getECAL_VERSION_MINOR() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_ECAL_VERSION_MINOR_swig_cd49d5ad85cbb53a())
	return swig_r
}

var ECAL_VERSION_MINOR int = _swig_getECAL_VERSION_MINOR()
func _swig_getECAL_VERSION_PATCH() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_ECAL_VERSION_PATCH_swig_cd49d5ad85cbb53a())
	return swig_r
}

var ECAL_VERSION_PATCH int = _swig_getECAL_VERSION_PATCH()
const ECAL_VERSION string = "0.0.0"
const ECAL_DATE string = "09.06.2020"
func _swig_getECAL_PLATFORMTOOLSET() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_ECAL_PLATFORMTOOLSET_swig_cd49d5ad85cbb53a()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

var ECAL_PLATFORMTOOLSET string = _swig_getECAL_PLATFORMTOOLSET()
func ECAL_GetVersionString() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_eCAL_GetVersionString_swig_cd49d5ad85cbb53a()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func ECAL_GetVersionDateString() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_eCAL_GetVersionDateString_swig_cd49d5ad85cbb53a()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func ECAL_GetVersion(arg1 *int, arg2 *int, arg3 *int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_GetVersion_swig_cd49d5ad85cbb53a(C.swig_voidp(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2)))
	return swig_r
}

func ECAL_Initialize(arg1 int, arg2 *string, arg3 string, arg4 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_eCAL_Initialize_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0), C.swig_voidp(_swig_i_1), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func ECAL_SetUnitName(arg1 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_SetUnitName_swig_cd49d5ad85cbb53a(*(*C.swig_type_5)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func ECAL_Finalize(arg1 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Finalize_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ECAL_IsInitialized(arg1 uint) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_IsInitialized_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ECAL_Ok() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_eCAL_Ok_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_FreeMem(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_eCAL_FreeMem_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0))
}

func ECAL_Event_gOpenEvent(arg1 string) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_eCAL_Event_gOpenEvent_swig_cd49d5ad85cbb53a(*(*C.swig_type_6)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func ECAL_Event_gCloseEvent(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Event_gCloseEvent_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Event_gSetEvent(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Event_gSetEvent_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Event_gWaitForEvent(arg1 uintptr, arg2 int64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Event_gWaitForEvent_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_type_7(_swig_i_1)))
	return swig_r
}

func ECAL_Event_gEventIsValid(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Event_gEventIsValid_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

const ECAL_Init_Publisher int = 0x01
const ECAL_Init_Subscriber int = 0x02
const ECAL_Init_Service int = 0x04
const ECAL_Init_Monitoring int = 0x08
const ECAL_Init_Logging int = 0x10
const ECAL_Init_TimeSync int = 0x20
const ECAL_Init_RPC int = 0x40
const ECAL_Init_ProcessReg int = 0x80
func _swig_geteCAL_Init_All() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_eCAL_Init_All_swig_cd49d5ad85cbb53a())
	return swig_r
}

var ECAL_Init_All int = _swig_geteCAL_Init_All()
func _swig_geteCAL_Init_Default() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_eCAL_Init_Default_swig_cd49d5ad85cbb53a())
	return swig_r
}

var ECAL_Init_Default int = _swig_geteCAL_Init_Default()
func ECAL_Logging_SetLogLevel(arg1 ECAL_Logging_eLogLevel) {
	_swig_i_0 := arg1
	C._wrap_eCAL_Logging_SetLogLevel_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0))
}

func ECAL_Logging_GetLogLevel() (_swig_ret ECAL_Logging_eLogLevel) {
	var swig_r ECAL_Logging_eLogLevel
	swig_r = (ECAL_Logging_eLogLevel)(C._wrap_eCAL_Logging_GetLogLevel_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Logging_Log(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_eCAL_Logging_Log_swig_cd49d5ad85cbb53a(*(*C.swig_type_8)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func ECAL_Logging_StartCoreTimer() {
	C._wrap_eCAL_Logging_StartCoreTimer_swig_cd49d5ad85cbb53a()
}

func ECAL_Logging_StopCoreTimer() {
	C._wrap_eCAL_Logging_StopCoreTimer_swig_cd49d5ad85cbb53a()
}

func ECAL_Logging_SetCoreTime(arg1 float64) {
	_swig_i_0 := arg1
	C._wrap_eCAL_Logging_SetCoreTime_swig_cd49d5ad85cbb53a(C.double(_swig_i_0))
}

func ECAL_Logging_GetCoreTime() (_swig_ret float64) {
	var swig_r float64
	swig_r = (float64)(C._wrap_eCAL_Logging_GetCoreTime_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Monitoring_SetExclFilter(arg1 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Monitoring_SetExclFilter_swig_cd49d5ad85cbb53a(*(*C.swig_type_9)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func ECAL_Monitoring_SetInclFilter(arg1 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Monitoring_SetInclFilter_swig_cd49d5ad85cbb53a(*(*C.swig_type_10)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func ECAL_Monitoring_SetFilterState(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Monitoring_SetFilterState_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ECAL_Monitoring_GetMonitoring(arg1 uintptr, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Monitoring_GetMonitoring_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Monitoring_GetLogging(arg1 uintptr, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Monitoring_GetLogging_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Monitoring_PubMonitoring(arg1 int, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Monitoring_PubMonitoring_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func ECAL_Monitoring_PubLogging(arg1 int, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Monitoring_PubLogging_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func ECAL_Process_DumpConfig() {
	C._wrap_eCAL_Process_DumpConfig_swig_cd49d5ad85cbb53a()
}

func ECAL_Process_GetHostName(arg1 uintptr, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Process_GetHostName_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Process_GetHostID() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_eCAL_Process_GetHostID_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Process_GetUnitName(arg1 uintptr, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Process_GetUnitName_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Process_GetTaskParameter(arg1 uintptr, arg2 int, arg3 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Process_GetTaskParameter_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func ECAL_Process_SleepMS(arg1 int64) {
	_swig_i_0 := arg1
	C._wrap_eCAL_Process_SleepMS_swig_cd49d5ad85cbb53a(C.swig_type_14(_swig_i_0))
}

func ECAL_Process_GetProcessID() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_eCAL_Process_GetProcessID_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Process_GetProcessName(arg1 uintptr, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Process_GetProcessName_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Process_GetProcessParameter(arg1 uintptr, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Process_GetProcessParameter_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Process_GetProcessCpuUsage() (_swig_ret float32) {
	var swig_r float32
	swig_r = (float32)(C._wrap_eCAL_Process_GetProcessCpuUsage_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Process_GetProcessMemory() (_swig_ret uint64) {
	var swig_r uint64
	swig_r = (uint64)(C._wrap_eCAL_Process_GetProcessMemory_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Process_GetSClock() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_eCAL_Process_GetSClock_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Process_GetSBytes() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_eCAL_Process_GetSBytes_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Process_GetWClock() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_eCAL_Process_GetWClock_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Process_GetWBytes() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_eCAL_Process_GetWBytes_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Process_GetRClock() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_eCAL_Process_GetRClock_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Process_GetRBytes() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_eCAL_Process_GetRBytes_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Process_SetState(arg1 ECAL_Process_eSeverity, arg2 ECAL_Process_eSeverity_Level, arg3 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_eCAL_Process_SetState_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), *(*C.swig_type_22)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func ECAL_Process_StartProcess(arg1 string, arg2 string, arg3 string, arg4 int, arg5 ECAL_Process_eStartMode, arg6 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_eCAL_Process_StartProcess_swig_cd49d5ad85cbb53a(*(*C.swig_type_23)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_24)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_25)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3), C.swig_intgo(_swig_i_4), C.swig_intgo(_swig_i_5)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func ECAL_Process_StopProcessName(arg1 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Process_StopProcessName_swig_cd49d5ad85cbb53a(*(*C.swig_type_26)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func ECAL_Process_StopProcessID(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Process_StopProcessID_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ECAL_Pub_New() (_swig_ret uintptr) {
	var swig_r uintptr
	swig_r = (uintptr)(C._wrap_eCAL_Pub_New_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Pub_Create(arg1 uintptr, arg2 string, arg3 string, arg4 string, arg5 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_eCAL_Pub_Create_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), *(*C.swig_type_27)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_28)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_29)(unsafe.Pointer(&_swig_i_3)), C.swig_intgo(_swig_i_4)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func ECAL_Pub_Destroy(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Pub_Destroy_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Pub_SetDescription(arg1 uintptr, arg2 string, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Pub_SetDescription_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), *(*C.swig_type_30)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func ECAL_Pub_ShareType(arg1 uintptr, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Pub_ShareType_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Pub_ShareDescription(arg1 uintptr, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Pub_ShareDescription_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Pub_SetQOS(arg1 uintptr, arg2 SWriterQOSC) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_eCAL_Pub_SetQOS_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func ECAL_Pub_GetQOS(arg1 uintptr, arg2 SWriterQOSC) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_eCAL_Pub_GetQOS_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func ECAL_Pub_SetLayerMode(arg1 uintptr, arg2 Enum_SS_eTransportLayerC, arg3 Enum_SS_eSendModeC) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Pub_SetLayerMode_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func ECAL_Pub_SetMaxBandwidthUDP(arg1 uintptr, arg2 int64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Pub_SetMaxBandwidthUDP_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_type_31(_swig_i_1)))
	return swig_r
}

func ECAL_Pub_SetID(arg1 uintptr, arg2 int64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Pub_SetID_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_type_32(_swig_i_1)))
	return swig_r
}

func ECAL_Pub_IsSubscribed(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Pub_IsSubscribed_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Pub_Send(arg1 uintptr, arg2 uintptr, arg3 int, arg4 int64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_eCAL_Pub_Send_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_type_33(_swig_i_3)))
	return swig_r
}

func ECAL_Pub_AddEventCallbackC(arg1 uintptr, arg2 ECAL_Publisher_Event, arg3 PubEventCallbackCT, arg4 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_eCAL_Pub_AddEventCallbackC_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3)))
	return swig_r
}

func ECAL_Pub_RemEventCallback(arg1 uintptr, arg2 ECAL_Publisher_Event) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Pub_RemEventCallback_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Pub_Dump(arg1 uintptr, arg2 uintptr, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Pub_Dump_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

type Enum_SS_eQOSPolicy_HistoryKindC int
func _swig_getkeep_last_history_qos() (_swig_ret Enum_SS_eQOSPolicy_HistoryKindC) {
	var swig_r Enum_SS_eQOSPolicy_HistoryKindC
	swig_r = (Enum_SS_eQOSPolicy_HistoryKindC)(C._wrap_keep_last_history_qos_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Keep_last_history_qos Enum_SS_eQOSPolicy_HistoryKindC = _swig_getkeep_last_history_qos()
func _swig_getkeep_all_history_qos() (_swig_ret Enum_SS_eQOSPolicy_HistoryKindC) {
	var swig_r Enum_SS_eQOSPolicy_HistoryKindC
	swig_r = (Enum_SS_eQOSPolicy_HistoryKindC)(C._wrap_keep_all_history_qos_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Keep_all_history_qos Enum_SS_eQOSPolicy_HistoryKindC = _swig_getkeep_all_history_qos()
type Enum_SS_eQOSPolicy_ReliabilityC int
func _swig_getbest_effort_reliability_qos() (_swig_ret Enum_SS_eQOSPolicy_ReliabilityC) {
	var swig_r Enum_SS_eQOSPolicy_ReliabilityC
	swig_r = (Enum_SS_eQOSPolicy_ReliabilityC)(C._wrap_best_effort_reliability_qos_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Best_effort_reliability_qos Enum_SS_eQOSPolicy_ReliabilityC = _swig_getbest_effort_reliability_qos()
func _swig_getreliable_reliability_qos() (_swig_ret Enum_SS_eQOSPolicy_ReliabilityC) {
	var swig_r Enum_SS_eQOSPolicy_ReliabilityC
	swig_r = (Enum_SS_eQOSPolicy_ReliabilityC)(C._wrap_reliable_reliability_qos_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Reliable_reliability_qos Enum_SS_eQOSPolicy_ReliabilityC = _swig_getreliable_reliability_qos()
type SwigcptrSWriterQOSC uintptr

func (p SwigcptrSWriterQOSC) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSWriterQOSC) SwigIsSWriterQOSC() {
}

func (arg1 SwigcptrSWriterQOSC) SetHistory_kind(arg2 Enum_SS_eQOSPolicy_HistoryKindC) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SWriterQOSC_history_kind_set_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSWriterQOSC) GetHistory_kind() (_swig_ret Enum_SS_eQOSPolicy_HistoryKindC) {
	var swig_r Enum_SS_eQOSPolicy_HistoryKindC
	_swig_i_0 := arg1
	swig_r = (Enum_SS_eQOSPolicy_HistoryKindC)(C._wrap_SWriterQOSC_history_kind_get_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSWriterQOSC) SetHistory_kind_depth(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SWriterQOSC_history_kind_depth_set_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSWriterQOSC) GetHistory_kind_depth() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SWriterQOSC_history_kind_depth_get_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSWriterQOSC) SetReliability(arg2 Enum_SS_eQOSPolicy_ReliabilityC) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SWriterQOSC_reliability_set_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSWriterQOSC) GetReliability() (_swig_ret Enum_SS_eQOSPolicy_ReliabilityC) {
	var swig_r Enum_SS_eQOSPolicy_ReliabilityC
	_swig_i_0 := arg1
	swig_r = (Enum_SS_eQOSPolicy_ReliabilityC)(C._wrap_SWriterQOSC_reliability_get_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSWriterQOSC() (_swig_ret SWriterQOSC) {
	var swig_r SWriterQOSC
	swig_r = (SWriterQOSC)(SwigcptrSWriterQOSC(C._wrap_new_SWriterQOSC_swig_cd49d5ad85cbb53a()))
	return swig_r
}

func DeleteSWriterQOSC(arg1 SWriterQOSC) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_SWriterQOSC_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0))
}

type SWriterQOSC interface {
	Swigcptr() uintptr
	SwigIsSWriterQOSC()
	SetHistory_kind(arg2 Enum_SS_eQOSPolicy_HistoryKindC)
	GetHistory_kind() (_swig_ret Enum_SS_eQOSPolicy_HistoryKindC)
	SetHistory_kind_depth(arg2 int)
	GetHistory_kind_depth() (_swig_ret int)
	SetReliability(arg2 Enum_SS_eQOSPolicy_ReliabilityC)
	GetReliability() (_swig_ret Enum_SS_eQOSPolicy_ReliabilityC)
}

type SwigcptrSReaderQOSC uintptr

func (p SwigcptrSReaderQOSC) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSReaderQOSC) SwigIsSReaderQOSC() {
}

func (arg1 SwigcptrSReaderQOSC) SetHistory_kind(arg2 Enum_SS_eQOSPolicy_HistoryKindC) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SReaderQOSC_history_kind_set_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSReaderQOSC) GetHistory_kind() (_swig_ret Enum_SS_eQOSPolicy_HistoryKindC) {
	var swig_r Enum_SS_eQOSPolicy_HistoryKindC
	_swig_i_0 := arg1
	swig_r = (Enum_SS_eQOSPolicy_HistoryKindC)(C._wrap_SReaderQOSC_history_kind_get_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSReaderQOSC) SetHistory_kind_depth(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SReaderQOSC_history_kind_depth_set_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSReaderQOSC) GetHistory_kind_depth() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_SReaderQOSC_history_kind_depth_get_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrSReaderQOSC) SetReliability(arg2 Enum_SS_eQOSPolicy_ReliabilityC) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_SReaderQOSC_reliability_set_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrSReaderQOSC) GetReliability() (_swig_ret Enum_SS_eQOSPolicy_ReliabilityC) {
	var swig_r Enum_SS_eQOSPolicy_ReliabilityC
	_swig_i_0 := arg1
	swig_r = (Enum_SS_eQOSPolicy_ReliabilityC)(C._wrap_SReaderQOSC_reliability_get_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewSReaderQOSC() (_swig_ret SReaderQOSC) {
	var swig_r SReaderQOSC
	swig_r = (SReaderQOSC)(SwigcptrSReaderQOSC(C._wrap_new_SReaderQOSC_swig_cd49d5ad85cbb53a()))
	return swig_r
}

func DeleteSReaderQOSC(arg1 SReaderQOSC) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_SReaderQOSC_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0))
}

type SReaderQOSC interface {
	Swigcptr() uintptr
	SwigIsSReaderQOSC()
	SetHistory_kind(arg2 Enum_SS_eQOSPolicy_HistoryKindC)
	GetHistory_kind() (_swig_ret Enum_SS_eQOSPolicy_HistoryKindC)
	SetHistory_kind_depth(arg2 int)
	GetHistory_kind_depth() (_swig_ret int)
	SetReliability(arg2 Enum_SS_eQOSPolicy_ReliabilityC)
	GetReliability() (_swig_ret Enum_SS_eQOSPolicy_ReliabilityC)
}

func ECAL_Server_Create(arg1 string) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_eCAL_Server_Create_swig_cd49d5ad85cbb53a(*(*C.swig_type_34)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func ECAL_Server_Destroy(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Server_Destroy_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Server_AddMethodCallbackC(arg1 uintptr, arg2 string, arg3 string, arg4 string, arg5 MethodCallbackCT, arg6 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5.Swigcptr()
	_swig_i_5 := arg6
	swig_r = (int)(C._wrap_eCAL_Server_AddMethodCallbackC_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), *(*C.swig_type_35)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_36)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_37)(unsafe.Pointer(&_swig_i_3)), C.uintptr_t(_swig_i_4), C.uintptr_t(_swig_i_5)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func ECAL_Server_RemMethodCallbackC(arg1 uintptr, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Server_RemMethodCallbackC_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), *(*C.swig_type_38)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func ECAL_Server_GetServiceName(arg1 uintptr, arg2 uintptr, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Server_GetServiceName_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func ECAL_Client_Create(arg1 string) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_eCAL_Client_Create_swig_cd49d5ad85cbb53a(*(*C.swig_type_39)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func ECAL_Client_Destroy(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Client_Destroy_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Client_SetHostName(arg1 uintptr, arg2 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Client_SetHostName_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), *(*C.swig_type_40)(unsafe.Pointer(&_swig_i_1))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func ECAL_Client_Call(arg1 uintptr, arg2 string, arg3 string, arg4 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_eCAL_Client_Call_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), *(*C.swig_type_41)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_42)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func ECAL_Client_Call_Wait(arg1 uintptr, arg2 string, arg3 string, arg4 string, arg5 int, arg6 Struct_SS_SServiceInfoC, arg7 uintptr, arg8 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	_swig_i_5 := arg6.Swigcptr()
	_swig_i_6 := arg7
	_swig_i_7 := arg8
	swig_r = (int)(C._wrap_eCAL_Client_Call_Wait_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), *(*C.swig_type_43)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_44)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_45)(unsafe.Pointer(&_swig_i_3)), C.swig_intgo(_swig_i_4), C.uintptr_t(_swig_i_5), C.uintptr_t(_swig_i_6), C.swig_intgo(_swig_i_7)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func ECAL_Client_AddResponseCallbackC(arg1 uintptr, arg2 ResponseCallbackCT, arg3 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Client_AddResponseCallbackC_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func ECAL_Client_RemResponseCallback(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Client_RemResponseCallback_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Sub_New() (_swig_ret uintptr) {
	var swig_r uintptr
	swig_r = (uintptr)(C._wrap_eCAL_Sub_New_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Sub_Create(arg1 uintptr, arg2 string, arg3 string, arg4 string, arg5 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_eCAL_Sub_Create_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), *(*C.swig_type_46)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_47)(unsafe.Pointer(&_swig_i_2)), *(*C.swig_type_48)(unsafe.Pointer(&_swig_i_3)), C.swig_intgo(_swig_i_4)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
	return swig_r
}

func ECAL_Sub_Destroy(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Sub_Destroy_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Sub_SetQOS(arg1 uintptr, arg2 SReaderQOSC) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_eCAL_Sub_SetQOS_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func ECAL_Sub_GetQOS(arg1 uintptr, arg2 SReaderQOSC) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int)(C._wrap_eCAL_Sub_GetQOS_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func ECAL_Sub_SetID(arg1 uintptr, arg2 *int64, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Sub_SetID_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func ECAL_Sub_Receive(arg1 uintptr, arg2 uintptr, arg3 int, arg4 *int64, arg5 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_eCAL_Sub_Receive_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_voidp(_swig_i_3), C.swig_intgo(_swig_i_4)))
	return swig_r
}

func ECAL_Sub_AddReceiveCallbackC(arg1 uintptr, arg2 ReceiveCallbackCT, arg3 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Sub_AddReceiveCallbackC_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func ECAL_Sub_RemReceiveCallback(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Sub_RemReceiveCallback_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Sub_AddEventCallbackC(arg1 uintptr, arg2 ECAL_Subscriber_Event, arg3 SubEventCallbackCT, arg4 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_eCAL_Sub_AddEventCallbackC_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.uintptr_t(_swig_i_2), C.uintptr_t(_swig_i_3)))
	return swig_r
}

func ECAL_Sub_RemEventCallback(arg1 uintptr, arg2 ECAL_Subscriber_Event) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Sub_RemEventCallback_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Sub_GetDescription(arg1 uintptr, arg2 uintptr, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Sub_GetDescription_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func ECAL_Sub_SetTimeout(arg1 uintptr, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Sub_SetTimeout_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Sub_Dump(arg1 uintptr, arg2 uintptr, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Sub_Dump_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func ECAL_Proto_Dyn_JSON_Sub_Create(arg1 string) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_eCAL_Proto_Dyn_JSON_Sub_Create_swig_cd49d5ad85cbb53a(*(*C.swig_type_49)(unsafe.Pointer(&_swig_i_0))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func ECAL_Proto_Dyn_JSON_Sub_Destroy(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Proto_Dyn_JSON_Sub_Destroy_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Proto_Dyn_JSON_Sub_AddReceiveCallbackC(arg1 uintptr, arg2 ReceiveCallbackCT, arg3 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Proto_Dyn_JSON_Sub_AddReceiveCallbackC_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2)))
	return swig_r
}

func ECAL_Proto_Dyn_JSON_Sub_RemReceiveCallback(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Proto_Dyn_JSON_Sub_RemReceiveCallback_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Time_GetName(arg1 uintptr, arg2 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (int)(C._wrap_eCAL_Time_GetName_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1)))
	return swig_r
}

func ECAL_Time_GetMicroSeconds() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_eCAL_Time_GetMicroSeconds_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Time_GetNanoSeconds() (_swig_ret int64) {
	var swig_r int64
	swig_r = (int64)(C._wrap_eCAL_Time_GetNanoSeconds_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Time_SetNanoSeconds(arg1 int64) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Time_SetNanoSeconds_swig_cd49d5ad85cbb53a(C.swig_type_52(_swig_i_0)))
	return swig_r
}

func ECAL_Time_IsTimeSynchronized() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_eCAL_Time_IsTimeSynchronized_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Time_IsTimeMaster() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_eCAL_Time_IsTimeMaster_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Time_SleepForNanoseconds(arg1 int64) {
	_swig_i_0 := arg1
	C._wrap_eCAL_Time_SleepForNanoseconds_swig_cd49d5ad85cbb53a(C.swig_type_53(_swig_i_0))
}

func ECAL_Time_GetStatus(arg1 *int, arg2 *string, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Time_GetStatus_swig_cd49d5ad85cbb53a(C.swig_voidp(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_intgo(_swig_i_2)))
	return swig_r
}

func ECAL_Timer_Create() (_swig_ret uintptr) {
	var swig_r uintptr
	swig_r = (uintptr)(C._wrap_eCAL_Timer_Create_swig_cd49d5ad85cbb53a())
	return swig_r
}

func ECAL_Timer_Destroy(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Timer_Destroy_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func ECAL_Timer_Start(arg1 uintptr, arg2 int, arg3 TimerCallbackCT, arg4 int, arg5 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	_swig_i_3 := arg4
	_swig_i_4 := arg5
	swig_r = (int)(C._wrap_eCAL_Timer_Start_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.uintptr_t(_swig_i_2), C.swig_intgo(_swig_i_3), C.uintptr_t(_swig_i_4)))
	return swig_r
}

func ECAL_Timer_Stop(arg1 uintptr) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_eCAL_Timer_Stop_swig_cd49d5ad85cbb53a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type Enum_SS_eTransportLayerC int
func _swig_gettlayer_none() (_swig_ret Enum_SS_eTransportLayerC) {
	var swig_r Enum_SS_eTransportLayerC
	swig_r = (Enum_SS_eTransportLayerC)(C._wrap_tlayer_none_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Tlayer_none Enum_SS_eTransportLayerC = _swig_gettlayer_none()
func _swig_gettlayer_udp_mc() (_swig_ret Enum_SS_eTransportLayerC) {
	var swig_r Enum_SS_eTransportLayerC
	swig_r = (Enum_SS_eTransportLayerC)(C._wrap_tlayer_udp_mc_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Tlayer_udp_mc Enum_SS_eTransportLayerC = _swig_gettlayer_udp_mc()
func _swig_gettlayer_shm() (_swig_ret Enum_SS_eTransportLayerC) {
	var swig_r Enum_SS_eTransportLayerC
	swig_r = (Enum_SS_eTransportLayerC)(C._wrap_tlayer_shm_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Tlayer_shm Enum_SS_eTransportLayerC = _swig_gettlayer_shm()
func _swig_gettlayer_inproc() (_swig_ret Enum_SS_eTransportLayerC) {
	var swig_r Enum_SS_eTransportLayerC
	swig_r = (Enum_SS_eTransportLayerC)(C._wrap_tlayer_inproc_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Tlayer_inproc Enum_SS_eTransportLayerC = _swig_gettlayer_inproc()
func _swig_gettlayer_all() (_swig_ret Enum_SS_eTransportLayerC) {
	var swig_r Enum_SS_eTransportLayerC
	swig_r = (Enum_SS_eTransportLayerC)(C._wrap_tlayer_all_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Tlayer_all Enum_SS_eTransportLayerC = _swig_gettlayer_all()
type Enum_SS_eSendModeC int
func _swig_getsmode_none() (_swig_ret Enum_SS_eSendModeC) {
	var swig_r Enum_SS_eSendModeC
	swig_r = (Enum_SS_eSendModeC)(C._wrap_smode_none_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Smode_none Enum_SS_eSendModeC = _swig_getsmode_none()
func _swig_getsmode_off() (_swig_ret Enum_SS_eSendModeC) {
	var swig_r Enum_SS_eSendModeC
	swig_r = (Enum_SS_eSendModeC)(C._wrap_smode_off_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Smode_off Enum_SS_eSendModeC = _swig_getsmode_off()
func _swig_getsmode_on() (_swig_ret Enum_SS_eSendModeC) {
	var swig_r Enum_SS_eSendModeC
	swig_r = (Enum_SS_eSendModeC)(C._wrap_smode_on_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Smode_on Enum_SS_eSendModeC = _swig_getsmode_on()
func _swig_getsmode_auto() (_swig_ret Enum_SS_eSendModeC) {
	var swig_r Enum_SS_eSendModeC
	swig_r = (Enum_SS_eSendModeC)(C._wrap_smode_auto_swig_cd49d5ad85cbb53a())
	return swig_r
}

var Smode_auto Enum_SS_eSendModeC = _swig_getsmode_auto()
func ECAL_Util_ShutdownUnitName(arg1 string) {
	_swig_i_0 := arg1
	C._wrap_eCAL_Util_ShutdownUnitName_swig_cd49d5ad85cbb53a(*(*C.swig_type_54)(unsafe.Pointer(&_swig_i_0)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
}

func ECAL_Util_ShutdownProcessID(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_eCAL_Util_ShutdownProcessID_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0))
}

func ECAL_Util_ShutdownProcesses() {
	C._wrap_eCAL_Util_ShutdownProcesses_swig_cd49d5ad85cbb53a()
}

func ECAL_Util_ShutdownCore() {
	C._wrap_eCAL_Util_ShutdownCore_swig_cd49d5ad85cbb53a()
}

func ECAL_Util_EnableLoopback(arg1 int) {
	_swig_i_0 := arg1
	C._wrap_eCAL_Util_EnableLoopback_swig_cd49d5ad85cbb53a(C.swig_intgo(_swig_i_0))
}

func ECAL_Util_GetTypeName(arg1 string, arg2 uintptr, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Util_GetTypeName_swig_cd49d5ad85cbb53a(*(*C.swig_type_55)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func ECAL_Util_GetDescription(arg1 string, arg2 uintptr, arg3 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_eCAL_Util_GetDescription_swig_cd49d5ad85cbb53a(*(*C.swig_type_56)(unsafe.Pointer(&_swig_i_0)), C.uintptr_t(_swig_i_1), C.swig_intgo(_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}


type ECAL_Process_eSeverity_Level int
type ECAL_Publisher_Event int
type ECAL_Subscriber_Event int
type ECAL_Logging_eLogLevel int
type ECAL_Process_eStartMode int
type ECAL_Process_eSeverity int

type SwigcptrStruct_SS_SServiceInfoC uintptr
type Struct_SS_SServiceInfoC interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStruct_SS_SServiceInfoC) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrPubEventCallbackCT uintptr
type PubEventCallbackCT interface {
	Swigcptr() uintptr;
}
func (p SwigcptrPubEventCallbackCT) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrMethodCallbackCT uintptr
type MethodCallbackCT interface {
	Swigcptr() uintptr;
}
func (p SwigcptrMethodCallbackCT) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrResponseCallbackCT uintptr
type ResponseCallbackCT interface {
	Swigcptr() uintptr;
}
func (p SwigcptrResponseCallbackCT) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrReceiveCallbackCT uintptr
type ReceiveCallbackCT interface {
	Swigcptr() uintptr;
}
func (p SwigcptrReceiveCallbackCT) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrSubEventCallbackCT uintptr
type SubEventCallbackCT interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSubEventCallbackCT) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrTimerCallbackCT uintptr
type TimerCallbackCT interface {
	Swigcptr() uintptr;
}
func (p SwigcptrTimerCallbackCT) Swigcptr() uintptr {
	return uintptr(p)
}

