// ========================= eCAL LICENSE =================================
//
// Copyright (C) 2016 - 2019 Continental Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ========================= eCAL LICENSE =================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: animal.proto

package pbexample

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Dog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Colour string `protobuf:"bytes,2,opt,name=colour,proto3" json:"colour,omitempty"`
}

func (x *Dog) Reset() {
	*x = Dog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_animal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dog) ProtoMessage() {}

func (x *Dog) ProtoReflect() protoreflect.Message {
	mi := &file_animal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dog.ProtoReflect.Descriptor instead.
func (*Dog) Descriptor() ([]byte, []int) {
	return file_animal_proto_rawDescGZIP(), []int{0}
}

func (x *Dog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dog) GetColour() string {
	if x != nil {
		return x.Colour
	}
	return ""
}

var File_animal_proto protoreflect.FileDescriptor

var file_animal_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x22, 0x31, 0x0a, 0x03, 0x44, 0x6f, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x75, 0x72, 0x42, 0x15, 0x5a, 0x13,
	0x70, 0x62, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x3b, 0x70, 0x62, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_animal_proto_rawDescOnce sync.Once
	file_animal_proto_rawDescData = file_animal_proto_rawDesc
)

func file_animal_proto_rawDescGZIP() []byte {
	file_animal_proto_rawDescOnce.Do(func() {
		file_animal_proto_rawDescData = protoimpl.X.CompressGZIP(file_animal_proto_rawDescData)
	})
	return file_animal_proto_rawDescData
}

var file_animal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_animal_proto_goTypes = []interface{}{
	(*Dog)(nil), // 0: pb.Animal.Dog
}
var file_animal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_animal_proto_init() }
func file_animal_proto_init() {
	if File_animal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_animal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_animal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_animal_proto_goTypes,
		DependencyIndexes: file_animal_proto_depIdxs,
		MessageInfos:      file_animal_proto_msgTypes,
	}.Build()
	File_animal_proto = out.File
	file_animal_proto_rawDesc = nil
	file_animal_proto_goTypes = nil
	file_animal_proto_depIdxs = nil
}
